### PR TITLE
mRKS examples

### PR DESCRIPTION
**Pull request by ymshi449**
Check here for details:
https://github.com/ymshi449/n2v_examples/blob/mRKS/mRKS/Nobel_Gas.ipynb

### CODE REVIEW

**Review by VHchavez — COMMENTED** [review]
Is there a negative result if a user-generated uniform grid is used? Seems like would be good for plotting, but for calculations? 

Also name for second file: Should be "Noble" instead of "Nobel"

**Comment by ymshi449** [comment]
A negative result?

**Comment by VHchavez** [comment]
As in how sensitive the method is to this rectangular grid. Since it's not dense around the nuclei, how easy it is to have a coarse grid that will result in an incorrect potential

**Comment by ymshi449** [comment]
The user-defined grid only works in plotting and everything is calculated in DFT spherical grid. So it does not matter about the accuracy. One can even plot the potential on 1 grid point if they what and the result should still be accurate.

**Comment by VHchavez** [comment]
I see, but do need to specify it at the beggining of the algorithm right?

**Comment by ymshi449** [comment]
Yes. Because the calculation of vxc on any grids needs local variables in mRKS() function.

**Review by VHchavez — APPROVED** [review]

**Pull request merged**
